### PR TITLE
Fix for Clippy not checking tests

### PR DESCRIPTION
**Pull request by Cypher1**
Small fix for 
 https://github.com/lowRISC/manticore/issues/80

### CODE REVIEW

**Comment by mcy** [comment]
Turns out Clippy doesn't like my tests. =)
Can you throw `#![allow(clippy::unusual_byte_groupings)]` on the crate root?

**Comment by mcy** [comment]
Please squash the new commit into the previous one, so that CI passes at each commit.

**Comment by Cypher1** [comment]
In my experience Github does that on commit, but I can do it manually.

**Comment by Cypher1** [comment]
I have squashed my commits and also rebased on main. I have also checked the changes locally to ensure no new lint issues were added.

**Review by alistair23 — APPROVED** [review]

**Comment by mcy** [comment]
We have this repo set up so that it rebases the PR branch on top of master and then splats the result onto master. It's useful for breaking a PR up into nice pieces and retaining their commit messages. =)

**Review by mcy — APPROVED** [review]

**Pull request merged**
